[package]
name = "vaccine_client"
version = "0.1.0"
authors = ["jordanbertasso <36979824+jordanbertasso@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.5"
