apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: let-me-in
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/hack-mac-2021-kctf/let-me-in-challenge:c8fe1d9248dfaff132fc6ee5afa462d87f77a049a2513d12120a24e54ab8c598
