version: "3"
services:
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: warehouse
        container_name: warehouse
        ports:
            - 1337:1337
